In [4]:
import numpy as np

In [19]:
## broadcast
left = np.array([10, 5])
right = np.array([[1, 2], [3, 4]])
print(left.shape)
print(right.shape)
print(left+right)

(2,)
(2, 2)
[[11  7]
 [13  9]]


In [11]:
## reference
a = np.array([[1, 2], [3, 4]])
print(a)
print()
b = a[:, 0]
print(b)
print()
b[0] = 10
print(a)

[[1 2]
 [3 4]]

[1 3]

[[10  2]
 [ 3  4]]


In [21]:
## LBYL: look before you leap
my_dict = {'name': 'zimu', 'age': 18}
try:
    gender = my_dict['gender']
except KeyError:
    print('key not exist in dict')
    place = None

key not exist in dict


In [31]:
## conj
conj_origin = np.arange(1., 2., 0.1)
print(conj_origin.shape)
print(conj_origin)
conj = conj_origin.conj()
print(conj.shape)
print(conj_origin.conj())

(10,)
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
(10,)
(10,)
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [ ]:
## scipy
# main scipy module:
# 1. integrate
# 2. optimize
# 3. linalg
# 4. stats

## pandas